-- SELECTION

/*
    41 ) WAQTD ALL THE DETAILS OF THE EMPLOYEES WHOSE SALARY 
      IS MORE THEN 1000 ?

*/
            SELECT SAL
            FROM SCOTT.EMP
            WHERE SAL > 1000;

/*
    42) WAQTD ENAME AND SALARY FOR THE EMPLOYEES WHOSE DEPTNO IS 20 ?
*/
            SELECT ENAME, SAL
            FROM SCOTT.EMP
            WHERE DEPTNO=20;

/*
   43) WAQTD JOB AND DEPTNO OF AN EMPLOYEES WHO ARE  WORKING 
      AS MANAGER ?
*/
            SELECT JOB,DEPTNO
            FROM SCOTT.EMP
            WHERE JOB = 'MANAGER' ;

/*
    44) WAQTD ALL THE DETAILS OF ALL THE EMPLOYEES WHOSE NAME IS KING ?
*/
        SELECT *
        FROM SCOTT.EMP
        WHERE ENAME= 'KING' ;

/*
     46) WAQTD HIREDATE AND DEPTNO OF AN EMPLOYEES WHO HIRED 
     AFTER THE 1981 ?
*/
        SELECT HIREDATE, DEPTNO
        FROM SCOTT.EMP
        WHERE HIREDATE > '31-DEC-1981' ; 

/*
    52) WAQTD ENAME AND JOB OF ALL THE EMPLOYEES EXCEPT THE
    EMPLOYEES OF DEPTNO 20 ?
*/

        SELECT ENAME, JOB
        FROM SCOTT.EMP
        WHERE DEPTNO NOT IN (20); 

/*
    55) WAQTD ALL THE DETAILS OF THE EMPLOYEES ALONG WITH THAT 
     20% HIKE OF IN THEIR SALARY FOR THE EMPLOYEES WHO HIRED
   AFTER 85 ?
*/
        SELECT EMP .* , SAL+SAL*20/100 AS "20% HIKE"
        FROM SCOTT.EMP
        WHERE HIREDATE > '31-DEC-85' ;

/*
    56) WAQTD ALL THE DETAILS OF THE EMPLOYEES ALONG WITH THAT 
     12% DEDUCTION  OF IN THEIR SALARY FOR THE EMPLOYEES WHO HIRED
   BEFORE  84 ?
*/
        SELECT EMP .*, SAL-SAL*12/100 AS "12% DEDUCTION"
        FROM SCOTT.EMP
        WHERE HIREDATE  < '01-JAN-84';

/*
    60) WAQTD ALL THE DETAILS OF THE EMPLOYEES ALONG WITH THAT 
     20% HIKE OF IN THEIR  HALF TERM SALARY FOR ALL THE EMPLOYEES
    WHOSE HALF TERM SALARY IS MORE THAN 7000 ?
*/
        SELECT EMP .* , SAL*6+SAL*20/100 AS "20% HIKE"
        FROM SCOTT.EMP
        WHERE SAL*6 > 7000;

                  

--  LOGICAL OPERATORS

/*
    61) WAQTD ALL THE DETAILS OF THE EMPLOYEES WHO ARE WORKING IN DEPTNO
     10 AND 20?
*/
        SELECT *
        FROM SCOTT.EMP
        WHERE (DEPTNO = 10 AND
              DEPTNO  = 20);

/*
    62) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHO ARE WORKING 
     AS MANAGER AND SALESMAN ?
*/
        
        SELECT *
        FROM SCOTT.EMP
        WHERE (JOB = 'MANAGER' AND
              JOB  = 'SALESMAN');

/*
    74) WAQTD ENAME AND ANNAUL SALARY WITH ALISAS NAME FOR THE                  
    E MPLOYEES WHOSE ANNUAL SALARY IS MORE THEN 800 IN DEPTNO 30 WORKING   AS SALESMAN AND HIRED BEFORE THE 88 ?
*/
        SELECT ENAME, SAL*12 AS "Annual sal"
        FROM SCOTT.EMP
        WHERE SAL*12 > 800 AND
              DEPTNO = 30 AND
              JOB = 'SALESMAN' AND
              HIREDATE < '31-DEC-88' ;

/*
    77) WAQTD JOB AND SALARY FOR THE EMPLOYEES WHOSE COMM IS LESS THEN 2000 AND SALARIES ARE MORE THEN 1000 IN DEPTNO 10, 20?
*/
        SELECT JOB,SAL
        FROM SCOTT.EMP
        WHERE COMM < 2000 AND
              SAL > 1000 AND
              DEPTNO IN (10,20);
/*
    80) ALL THE DETAILS AND HALF TERM SALARY FOR SALESMAN AND MANAGER IN DEPTNO 10,30 ?
*/
        SELECT EMP .* , SAL*6 AS "HALFTERM SAL"
        FROM SCOTT.EMP
        WHERE JOB = 'SALESMAN' AND
              JOB = 'MANAGER' AND
              DEPTNO IN (10,30);



-- SPECIAL OPERATOR

/*
    81) WAQTD ALL THE DETAILS OF THE EMPLOYEES WHO ARE WORKING IN DEPTNO
     10 AND 20?
*/
        SELECT *
        FROM SCOTT.EMP
        WHERE DEPTNO IN (10,20);

/*
    87) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE SAL IS 
      3000 AND 5000 ?
*/
        SELECT *
        FROM SCOTT.EMP
        WHERE SAL IN (3000, 5000);

/*
    107) WAQTD ANNAUL SALARY OF THE EMPLOYEE WHO ARE NOT EARNING COMMISSION ?
*/
        SELECT SAL*12 AS "ANNUAL SAL"
        FROM SCOTT.EMP
        WHERE COMM IS NULL;

/*
    108) WAQTD ALL THE DETAILS WITH ANNAUL COMMISSION FOR THE EMPLOYEE WHO  ARE WORKING IN DEPT 10 AND DONT HAVE ANY REPORTING MANAGER ?
*/
        SELECT EMP.* , COMM*12 AS "ANNUAL COMM"
        FROM SCOTT.EMP
        WHERE DEPTNO = 10 AND
        MGR IS NULL;

/*
    101) ) WAQTD ALL THE DETAILS OF THE EMPLOYEES WHOSE HIRED BETWEEN 81 TO 89  INTO DEPTNO 20 ?
*/
        SELECT *
        FROM SCOTT.EMP
        WHERE HIREDATE BETWEEN '01-JAN-81' AND
                                '31-DEC-89' AND
              DEPTNO = 20;

/*
    123) WAQTD ALL THE DETAILS OF THE EMPLOYEE EXCEPT 
    WHOSE NAME HAVING A ?
*/
        SELECT *
        FROM SCOTT.EMP
        WHERE ENAME NOT LIKE '%A%';

/*
    125) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE 
    NAME HAVING 2 TIME CONSUGATIVE. A ?
*/
        SELECT *
        FROM SCOTT.EMP
        WHERE ENAME LIKE '%AA%';

/*
    130) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME START 
    WITH % HAVING 4TH CHARACTER _ AND ENDS WITH % ?

   CAN BE SOVED WITH REGULAR EXPRESSION
*/
        -- SELECT *
        -- FROM SCOTT.EMP
        -- WHERE ENAME LIKE '_%' AND
        --       ENAME LIKE '%%%_' AND
        --       ENAME LIKE '%_' ;

/*
    131) WAQTD MAX SALARY FROM THE EMPLOYEE TABLE ?
*/
        SELECT MAX(SAL)
        FROM SCOTT.EMP;